#!/usr/bin/env python3
"""Package exported OSRacer policy artifacts for Jetson deployment."""

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ASSETS_SRC = REPO_ROOT / "source" / "osracer_lab_assets"
if str(ASSETS_SRC) not in sys.path:
    sys.path.insert(0, str(ASSETS_SRC))

from osracer_lab_assets.hardware_params import hardware_summary


def parse_args():
    parser = argparse.ArgumentParser(description="Package OSRacer policy artifacts for Jetson.")
    parser.add_argument("--policy", required=True, help="Exported policy file, for example policy.pt")
    parser.add_argument("--output-dir", required=True, help="Deployment package output directory")
    parser.add_argument("--name", default="osracer_jetson_deployment", help="Package name written to manifest")
    parser.add_argument("--task", default="Isaac-OSRacerDriftRL-v0")
    parser.add_argument("--format", default="torchscript", choices=("torchscript", "onnx", "tensorrt"))
    parser.add_argument("--measured-overlay", default=None, help="Optional measured overlay JSON to include")
    parser.add_argument("--notes", default="", help="Short operator note for the manifest")
    return parser.parse_args()


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def git_value(args):
    try:
        return subprocess.check_output(args, cwd=REPO_ROOT, text=True, stderr=subprocess.DEVNULL).strip()
    except Exception:
        return None


def write_json(path, payload):
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")


def readme_text(package_name, policy_name, task, package_format):
    if package_format == "torchscript":
        runtime_note = f"""## Runtime Preflight

```bash
tools/jetson_preflight.sh --policy /path/to/this/package/{policy_name} --offline-smoke
```
"""
    elif package_format == "onnx":
        runtime_note = (
            "## TensorRT Build\n\n"
            "Build the TensorRT engine on the target Jetson after applying the runtime performance profile:\n\n"
            "```bash\n"
            "tools/build_tensorrt_engine.sh \\\n"
            f"  --onnx /path/to/this/package/{policy_name} \\\n"
            "  --engine /path/to/this/package/policy_fp16.engine \\\n"
            "  --fp16 \\\n"
            "  --workspace-mb 1024\n"
            "```\n"
        )
    else:
        runtime_note = f"""## TensorRT Runtime Artifact

`{policy_name}` is a TensorRT engine. Verify this package on the target Jetson so
`tools/verify_jetson_deployment.py` can run its structural engine check and use
`trtexec --loadEngine` when TensorRT tools are installed.
"""

    return f"""# {package_name}

This OSRacer Jetson deployment package was generated by `scripts/package_jetson_deployment.py`.

## Contents

- `{policy_name}`: exported policy artifact
- `hardware_params.json`: hardware/runtime parameter snapshot
- `measured_overlay.json`: optional measured parameter overlay when packaged
- `manifest.json`: source repo, artifact metadata, and action contract
- `SHA256SUMS`: checksums for all package files

## Verify On Jetson

```bash
sha256sum -c SHA256SUMS
tools/verify_jetson_deployment.py /path/to/this/package
```

If this is a structure-only smoke package, add `--skip-policy-load`.

{runtime_note}
## Contract

- task: `{task}`
- format: `{package_format}`
- action: `[target_speed_mps, target_steering_rad]`
- initial max speed: `0.3 m/s`
- max steering: `0.488 rad`
- command topic: `/ackermann_cmd`
"""


def main():
    args = parse_args()
    policy_path = Path(args.policy).resolve()
    if not policy_path.is_file():
        raise FileNotFoundError(policy_path)

    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    policy_out = output_dir / policy_path.name
    hardware_out = output_dir / "hardware_params.json"
    readme_out = output_dir / "README.md"
    manifest_out = output_dir / "manifest.json"
    sha_out = output_dir / "SHA256SUMS"
    overlay_out = output_dir / "measured_overlay.json"

    shutil.copy2(policy_path, policy_out)
    write_json(hardware_out, hardware_summary())
    overlay_path = Path(args.measured_overlay).resolve() if args.measured_overlay else None
    if overlay_path:
        if not overlay_path.is_file():
            raise FileNotFoundError(overlay_path)
        shutil.copy2(overlay_path, overlay_out)
    readme_out.write_text(readme_text(args.name, policy_out.name, args.task, args.format))

    manifest = {
        "schema_version": 1,
        "name": args.name,
        "created_unix_s": int(time.time()),
        "task": args.task,
        "format": args.format,
        "notes": args.notes,
        "repo": {
            "root": str(REPO_ROOT),
            "head": git_value(["git", "rev-parse", "HEAD"]),
            "branch": git_value(["git", "branch", "--show-current"]),
            "dirty": bool(git_value(["git", "status", "--porcelain"])),
        },
        "artifacts": {
            policy_out.name: {
                "source": str(policy_path),
                "bytes": policy_out.stat().st_size,
                "sha256": sha256(policy_out),
            },
            hardware_out.name: {
                "source": "osracer_lab_assets.hardware_params",
                "bytes": hardware_out.stat().st_size,
                "sha256": sha256(hardware_out),
            },
            readme_out.name: {
                "source": "generated package instructions",
                "bytes": readme_out.stat().st_size,
                "sha256": sha256(readme_out),
            },
        },
        "runtime_contract": {
            "action": "[target_speed_mps, target_steering_rad]",
            "initial_max_speed_mps": hardware_summary()["chassis"]["initial_real_test_max_speed_mps"],
            "max_steering_rad": hardware_summary()["chassis"]["simulation_max_steering_rad"],
            "ackermann_topic": hardware_summary()["real_runtime"]["ackermann_cmd_topic"],
        },
    }
    if overlay_path:
        manifest["artifacts"][overlay_out.name] = {
            "source": str(overlay_path),
            "bytes": overlay_out.stat().st_size,
            "sha256": sha256(overlay_out),
            "optional": True,
            "kind": "measured_overlay",
        }
        manifest["measured_overlay"] = {
            "included": True,
            "artifact": overlay_out.name,
        }
    else:
        manifest["measured_overlay"] = {"included": False}
    write_json(manifest_out, manifest)

    lines = []
    package_files = [policy_out, hardware_out, readme_out, manifest_out]
    if overlay_path:
        package_files.insert(2, overlay_out)
    for path in package_files:
        lines.append(f"{sha256(path)}  {path.name}")
    sha_out.write_text("\n".join(lines) + "\n")

    print(f"wrote {output_dir}")
    for path in package_files + [sha_out]:
        print(f"  {path.name} ({path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
